title: Joe Boyle
subtitle: Joseph Scott Boyle (he/him)

description: Researcher, science communicator, and diver supporting people as nature
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joescottboyle.github.io" # the base hostname & protocol for your site
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-sitemap
